/*
Copyright (c) 2021 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by generate-imagename-constants.sh. DO NOT EDIT.

package charts

const (
	// ImageNameUalertmanager is a constant for an image in the image vector with name 'alertmanager'.
	ImageNameAlertmanager = "alertmanager"
	// ImageNameUalpine is a constant for an image in the image vector with name 'alpine'.
	ImageNameAlpine = "alpine"
	// ImageNameUalpineUiptables is a constant for an image in the image vector with name 'alpine-iptables'.
	ImageNameAlpineIptables = "alpine-iptables"
	// ImageNameUapiserverUproxy is a constant for an image in the image vector with name 'apiserver-proxy'.
	ImageNameApiserverProxy = "apiserver-proxy"
	// ImageNameUapiserverUproxyUpodUwebhook is a constant for an image in the image vector with name 'apiserver-proxy-pod-webhook'.
	ImageNameApiserverProxyPodWebhook = "apiserver-proxy-pod-webhook"
	// ImageNameUapiserverUproxyUsidecar is a constant for an image in the image vector with name 'apiserver-proxy-sidecar'.
	ImageNameApiserverProxySidecar = "apiserver-proxy-sidecar"
	// ImageNameUblackboxUexporter is a constant for an image in the image vector with name 'blackbox-exporter'.
	ImageNameBlackboxExporter = "blackbox-exporter"
	// ImageNameUclusterUautoscaler is a constant for an image in the image vector with name 'cluster-autoscaler'.
	ImageNameClusterAutoscaler = "cluster-autoscaler"
	// ImageNameUconfigmapUreloader is a constant for an image in the image vector with name 'configmap-reloader'.
	ImageNameConfigmapReloader = "configmap-reloader"
	// ImageNameUcoredns is a constant for an image in the image vector with name 'coredns'.
	ImageNameCoredns = "coredns"
	// ImageNameUdependencyUwatchdog is a constant for an image in the image vector with name 'dependency-watchdog'.
	ImageNameDependencyWatchdog = "dependency-watchdog"
	// ImageNameUetcdUdruid is a constant for an image in the image vector with name 'etcd-druid'.
	ImageNameEtcdDruid = "etcd-druid"
	// ImageNameUfluentUbit is a constant for an image in the image vector with name 'fluent-bit'.
	ImageNameFluentBit = "fluent-bit"
	// ImageNameUfluentUbitUpluginUinstaller is a constant for an image in the image vector with name 'fluent-bit-plugin-installer'.
	ImageNameFluentBitPluginInstaller = "fluent-bit-plugin-installer"
	// ImageNameUgardenerUresourceUmanager is a constant for an image in the image vector with name 'gardener-resource-manager'.
	ImageNameGardenerResourceManager = "gardener-resource-manager"
	// ImageNameUgardenerUseedUadmissionUcontroller is a constant for an image in the image vector with name 'gardener-seed-admission-controller'.
	ImageNameGardenerSeedAdmissionController = "gardener-seed-admission-controller"
	// ImageNameUgardenlet is a constant for an image in the image vector with name 'gardenlet'.
	ImageNameGardenlet = "gardenlet"
	// ImageNameUgrafana is a constant for an image in the image vector with name 'grafana'.
	ImageNameGrafana = "grafana"
	// ImageNameUhvpaUcontroller is a constant for an image in the image vector with name 'hvpa-controller'.
	ImageNameHvpaController = "hvpa-controller"
	// ImageNameUhyperkube is a constant for an image in the image vector with name 'hyperkube'.
	ImageNameHyperkube = "hyperkube"
	// ImageNameUingressUdefaultUbackend is a constant for an image in the image vector with name 'ingress-default-backend'.
	ImageNameIngressDefaultBackend = "ingress-default-backend"
	// ImageNameUistioUistiod is a constant for an image in the image vector with name 'istio-istiod'.
	ImageNameIstioIstiod = "istio-istiod"
	// ImageNameUistioUproxy is a constant for an image in the image vector with name 'istio-proxy'.
	ImageNameIstioProxy = "istio-proxy"
	// ImageNameUkubeUapiserver is a constant for an image in the image vector with name 'kube-apiserver'.
	ImageNameKubeApiserver = "kube-apiserver"
	// ImageNameUkubeUcontrollerUmanager is a constant for an image in the image vector with name 'kube-controller-manager'.
	ImageNameKubeControllerManager = "kube-controller-manager"
	// ImageNameUkubeUproxy is a constant for an image in the image vector with name 'kube-proxy'.
	ImageNameKubeProxy = "kube-proxy"
	// ImageNameUkubeUrbacUproxy is a constant for an image in the image vector with name 'kube-rbac-proxy'.
	ImageNameKubeRbacProxy = "kube-rbac-proxy"
	// ImageNameUkubeUscheduler is a constant for an image in the image vector with name 'kube-scheduler'.
	ImageNameKubeScheduler = "kube-scheduler"
	// ImageNameUkubeUstateUmetrics is a constant for an image in the image vector with name 'kube-state-metrics'.
	ImageNameKubeStateMetrics = "kube-state-metrics"
	// ImageNameUkubernetesUdashboard is a constant for an image in the image vector with name 'kubernetes-dashboard'.
	ImageNameKubernetesDashboard = "kubernetes-dashboard"
	// ImageNameUkubernetesUdashboardUmetricsUscraper is a constant for an image in the image vector with name 'kubernetes-dashboard-metrics-scraper'.
	ImageNameKubernetesDashboardMetricsScraper = "kubernetes-dashboard-metrics-scraper"
	// ImageNameUloki is a constant for an image in the image vector with name 'loki'.
	ImageNameLoki = "loki"
	// ImageNameUlokiUcurator is a constant for an image in the image vector with name 'loki-curator'.
	ImageNameLokiCurator = "loki-curator"
	// ImageNameUmetricsUserver is a constant for an image in the image vector with name 'metrics-server'.
	ImageNameMetricsServer = "metrics-server"
	// ImageNameUnginxUingressUcontroller is a constant for an image in the image vector with name 'nginx-ingress-controller'.
	ImageNameNginxIngressController = "nginx-ingress-controller"
	// ImageNameUnginxUingressUcontrollerUseed is a constant for an image in the image vector with name 'nginx-ingress-controller-seed'.
	ImageNameNginxIngressControllerSeed = "nginx-ingress-controller-seed"
	// ImageNameUnodeUexporter is a constant for an image in the image vector with name 'node-exporter'.
	ImageNameNodeExporter = "node-exporter"
	// ImageNameUnodeUlocalUdns is a constant for an image in the image vector with name 'node-local-dns'.
	ImageNameNodeLocalDns = "node-local-dns"
	// ImageNameUnodeUproblemUdetector is a constant for an image in the image vector with name 'node-problem-detector'.
	ImageNameNodeProblemDetector = "node-problem-detector"
	// ImageNameUpauseUcontainer is a constant for an image in the image vector with name 'pause-container'.
	ImageNamePauseContainer = "pause-container"
	// ImageNameUprometheus is a constant for an image in the image vector with name 'prometheus'.
	ImageNamePrometheus = "prometheus"
	// ImageNameUpromtail is a constant for an image in the image vector with name 'promtail'.
	ImageNamePromtail = "promtail"
	// ImageNameUtelegraf is a constant for an image in the image vector with name 'telegraf'.
	ImageNameTelegraf = "telegraf"
	// ImageNameUvpaUadmissionUcontroller is a constant for an image in the image vector with name 'vpa-admission-controller'.
	ImageNameVpaAdmissionController = "vpa-admission-controller"
	// ImageNameUvpaUexporter is a constant for an image in the image vector with name 'vpa-exporter'.
	ImageNameVpaExporter = "vpa-exporter"
	// ImageNameUvpaUrecommender is a constant for an image in the image vector with name 'vpa-recommender'.
	ImageNameVpaRecommender = "vpa-recommender"
	// ImageNameUvpaUupdater is a constant for an image in the image vector with name 'vpa-updater'.
	ImageNameVpaUpdater = "vpa-updater"
	// ImageNameUvpnUseed is a constant for an image in the image vector with name 'vpn-seed'.
	ImageNameVpnSeed = "vpn-seed"
	// ImageNameUvpnUseedUserver is a constant for an image in the image vector with name 'vpn-seed-server'.
	ImageNameVpnSeedServer = "vpn-seed-server"
	// ImageNameUvpnUshoot is a constant for an image in the image vector with name 'vpn-shoot'.
	ImageNameVpnShoot = "vpn-shoot"
	// ImageNameUvpnUshootUclient is a constant for an image in the image vector with name 'vpn-shoot-client'.
	ImageNameVpnShootClient = "vpn-shoot-client"
)
